apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coming-soon
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - networkpolicy.yaml
  - ingress.yaml
images:
  - name: coming-soon-backend
    newName: registry.example.com/coming-soon/backend
    newTag: "1.0.0"
  - name: coming-soon-frontend
    newName: registry.example.com/coming-soon/frontend
    newTag: "1.0.0"
  - name: coming-soon-db
    newName: registry.example.com/coming-soon/db
    newTag: "1.0.0"
